services:
  database:
    image: postgres:latest
    container_name: laxy-database
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=laxy-database
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: