server:
  log_level: debug

metrics:
  global:
    scrape_interval: 15s
    remote_write:
      - url: http://${REMOTE_WRITE_HOST:-localhost:9009}/api/v1/push
  configs:
    - name: default
      scrape_configs:
        - job_name: laxy-app
          static_configs:
            - targets: ['${LAXY_HOST:-localhost:8080}']

logs:
  configs:
    - name: default
      clients:
        - url: http://${LOKI_HOST:-loki:3100}/loki/api/v1/push
      positions:
        filename: /tmp/positions.yaml
      scrape_configs:
        - job_name: docker-logs
          docker_sd_configs:
            - host: unix:///var/run/docker.sock
              refresh_interval: 5s
          relabel_configs:
            - source_labels: [__meta_docker_container_name]
              regex: "/(.+)"
              target_label: container
            - source_labels: [__meta_docker_container_log_stream]
              target_label: stream

traces:
  configs:
    - name: default
      receivers:
        otlp:
          protocols:
            grpc:
            http:
      remote_write:
        - endpoint: ${TEMPO_HOST:-tempo:4317}
          insecure: true

integrations:
  metrics:
    autoscrape:
      enable: true
      metrics_instance: default

  agent:
    extra_labels:
      cluster: docker-compose
      namespace: docker-compose
      container: grafana-agent
      pod: grafana-agent-${HOSTNAME:-example}
