services:
#  laxy-app:
#    build:
#      context: .
#    container_name: laxy-app
#    restart: unless-stopped
#    hostname: laxy
#    environment:
#      - POSTGRES_URL=jdbc:postgresql://database:5432/laxy-database
#    ports:
#      - "8080:8080"
#    depends_on:
#      - database

  database:
    image: postgres:latest
    container_name: laxy-database
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=laxy-database
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=docker
    ports:
      - "5555:80"
    depends_on:
      - database

volumes:
  postgres_data: